variable "namespace" {
  description = "Kubernetes namespace for the observability stack"
  type        = string
  default     = "observability"
}

variable "storage_class" {
  description = "Storage class for persistent volumes (set automatically by cloud wrappers)"
  type        = string
}

variable "prometheus_retention" {
  description = "Prometheus data retention period"
  type        = string
  default     = "15d"
}

variable "prometheus_storage_size" {
  description = "Persistent volume size for Prometheus"
  type        = string
  default     = "50Gi"
}

variable "alertmanager_storage_size" {
  description = "Persistent volume size for Alertmanager"
  type        = string
  default     = "10Gi"
}

variable "grafana_enabled" {
  description = "Deploy Grafana alongside Prometheus"
  type        = bool
  default     = true
}

variable "grafana_admin_password" {
  description = "Grafana admin password"
  type        = string
  sensitive   = true
}

variable "grafana_storage_size" {
  description = "Persistent volume size for Grafana"
  type        = string
  default     = "10Gi"
}

variable "loki_enabled" {
  description = "Deploy Loki for log aggregation"
  type        = bool
  default     = false
}

variable "loki_storage_size" {
  description = "Persistent volume size for Loki"
  type        = string
  default     = "50Gi"
}

variable "otel_enabled" {
  description = "Deploy OpenTelemetry Collector"
  type        = bool
  default     = false
}

variable "ingress_enabled" {
  description = "Expose Grafana and Prometheus via ingress"
  type        = bool
  default     = false
}

variable "ingress_class" {
  description = "Ingress class name (set automatically by cloud wrappers)"
  type        = string
  default     = "nginx"
}

variable "grafana_ingress_host" {
  description = "Hostname for Grafana ingress"
  type        = string
  default     = ""
}

variable "alertmanager_slack_webhook" {
  description = "Slack webhook URL for Alertmanager notifications"
  type        = string
  sensitive   = true
  default     = ""
}

variable "alertmanager_pagerduty_key" {
  description = "PagerDuty routing key for Alertmanager notifications"
  type        = string
  sensitive   = true
  default     = ""
}

variable "service_account_annotations" {
  description = "Annotations for the Prometheus service account (e.g. IRSA on AWS, Workload Identity on GCP)"
  type        = map(string)
  default     = {}
}

variable "ithildin_rules" {
  description = "Prometheus alerting rules YAML generated by Ithildin (https://github.com/balakrishnan-vasudevan/ithildin)"
  type        = string
  default     = ""
}
